### ISSUE TITLE
Uncaught Error: Cannot find module 'C:/www\PayPooh/folderNotes.config.json'

### ISSUE THREAD

**Issue by jeucasulo** [Matthew-Carr/FolderNotes#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [folder-notes](https://github.com/Matthew-Carr/FolderNotes) package 0.1.0

### Stack Trace

Uncaught Error: Cannot find module 'C:\www\PayPooh/folderNotes.config.json'

```
At module.js:545

Error: Cannot find module 'C:\www\PayPooh/folderNotes.config.json'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/folder-notes/lib/folder-notes.js:90:14)
    at /packages/folder-notes/lib/folder-notes.js:164:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:1:623185)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3044548)
    at Package.activateConfig (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3033907)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:907432)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2945211)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2935491)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2935314)
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2943444
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2945462
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:1188425)
    at PackageManager.t.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:916612)
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:914021
    at r (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:908551)
    at o (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:1037432)
    at t.bufferStream (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:1037586)
    at Socket.e.on (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:1036188)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
     -3:11.8.0 editor:select-to-first-character-of-line (input.hidden-input)
     -3:11.6.0 core:cut (input.hidden-input)
     -3:10.9.0 command-palette:toggle (input.hidden-input)
  2x -3:06.9.0 core:move-down (input.hidden-input)
  2x -3:04.5.0 core:move-up (input.hidden-input)
     -3:03.9.0 core:confirm (input.hidden-input)
     -3:03.9.0 settings-view:install-packages-and-themes (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.26 
folder-notes 0.1.0 
open-folder 1.5.0 
platformio-ide-terminal 2.8.4 
```

**Comment by Matthematic** [comment]
That file is for the config that holds the note strings. The code was assuming it existed and had no fallback when it didn't. I've fixed it and added some instructions. 

As a side note, I made this atom package just for fun in a couple hours to see how atom packages worked, I never expected it would get any downloads other than me. I feel like a real developer now 😃 
This means I'll be cleaning up the code quite a bit and adding a lot more features soon.
